default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: nico-manager_development

test:
  <<: *default
  database: nico-manager_test

production:
  <<: *default
  database: nico-manager_production
  username: nico-manager
  password: <%= ENV['NICO-MANAGER_DATABASE_PASSWORD'] %>
