# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cb8462fbbed542a1e98ffd22a6d0d4fa10f881d4e28b3bfb265ed30a042b7f2629bc30bef081d3dfb7e1adf4178209cc922b01552a2e2bed9b85b0c6c809924

test:
  secret_key_base: 8479c08b7b995f40fa2a8a11244b20f7db3dad76ab44629ada325bdf95f0e3cb468c87993e6aa045d9c3a8114adabd3e648247bbe87976293b6a51200b0a4f99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
